### ISSUE TITLE
Slow UI with large number of torrents

### ISSUE THREAD

**Issue by 13werwolf13** [anlar/tewi#13]
First of all, I want to say thank you for your work, this project is what I was missing in my infrastructure.

But after finishing [packaging it for opensuse](https://build.opensuse.org/package/show/home:Werwolf2517/tewi), I ran into an interesting problem:

1) when connecting to my server with transmission-daemon, one core out of 20 is loaded at 100%

2) tui applications are very slow, from launch to the appearance of the list of hands it takes about 10 minutes, from pressing `?` to the appearance of help it takes about 6 minutes

I suspect that the matter is in the large number of hands (currently 1880)

I tried to write asciinema, but I couldn't complete the process in a normal way..

**Comment by anlar** [comment]
Could you confirm your Transmission version and what terminal emulator you are using?

I will be able further investigate issue only after I will implement proper logging in Tewi.

**Comment by 13werwolf13** [comment]
> Could you confirm your Transmission version and what terminal emulator you are using?

```shell
[werwolf@home] ~  
❯ ssh power transmission-daemon --version
transmission-daemon 4.0.6 (38c164933e)

[werwolf@home] ~  
❯ yakuake --version
yakuake 24.08.2
```

in fact, the terminal emulator is not important, I checked several and the situation does not change

I can assume that there are two reasons:
1) tewi requests information from transmission constantly without pauses (the official qt client and Android client pause 10 seconds between requests)
2) The process outputting information and the process making requests are not asynchronous and block each other
I am not a developer and know python too poorly to confirm or refute these theories.

**Comment by anlar** [comment]
Indeed it was not async. I kinda expected that textual workers will be async by default.

Made if fully async in the latest master. Also you could setup refresh interval by `--refresh-interval` option now (default is 5 seconds).

Though UI is not very snappy anyway with such large amount of items. I would expect it to be useful in real life only after implementing such features as pagination, filtering and search. For now only compact mode will speed up it somehow.

**Comment by 13werwolf13** [comment]
> Indeed it was not async. I kinda expected that textual workers will be async by default.
> 
> Made if fully async in the latest master. Also you could setup refresh interval by `--refresh-interval` option now (default is 5 seconds).
> 
> Though UI is not very snappy anyway with such large amount of items. I would expect it to be useful in real life only after implementing such features as pagination, filtering and search. For now only compact mode will speed up it somehow.

I picked up the latest master, but I didn’t see any significant changes in it in terms of performance, the situation is exactly the same as in the last tag.

**Comment by anlar** [comment]
Afraid I am at a loss for now. I can't reproduce this behavior myself. There may be another chance to find cause when I implement logging: https://github.com/anlar/tewi/issues/18

**Comment by 13werwolf13** [comment]
In order to find the answer, I tried to create a flamegraph using py-spy, but it didn’t work. Maybe it’s not suitable for interactive Python programs, or I’m missing something. Do you have any experience with this?

**Comment by 13werwolf13** [comment]
I created a flamegraph using py-spy. Here, tewi is running, data is collected from transmission-daemon, and the exit button `q` is pressed.

![profile](https://github.com/user-attachments/assets/adbd9f7e-1465-40c4-974c-2e54fbe638f3)

**Comment by 13werwolf13** [comment]
I found out empirically that changing the limit of displayed torrents really changes the situation
at 10 tewi works fine
at 500 it's slow, but usable
when the number is 1000 it is no longer possible to use

I also launched tewi with a minimum set of parameters, waited to receive data from the transmission, pressed the down arrow twice, went to the torrent in a couple of minutes and pressed q. I am attaching the log.
I can say that in the latest version in master, even with a large number of torrents, tewi works faster than before. but you can still use it only by limiting the limit of displayed torrents; without a limit, even completing the process takes almost a minute.

[tewi.log](https://github.com/user-attachments/files/17488175/tewi.log)

**Comment by anlar** [comment]
Okay, it seems that with Textual I won't be able to implement single list with large number of widgets. So it will be unusable in such cases until pagination implementation in #30 .

**Comment by anlar** [comment]
@13werwolf13 , could you try version from `pagination-wip` branch. It contains pagination implementation.

**Comment by 13werwolf13** [comment]
> @13werwolf13 , could you try version from `pagination-wip` branch. It contains pagination implementation.

YES! Now everything is working fine, I checked several actions and looked through my torrents for about ten minutes and did not find a single reason to say "everything is bad". I think we can say that a solution has been found.

**Comment by anlar** [comment]
Thank you for your assistance in debug. I will include pagination in v0.4.0.
